services:
  - type: web
    name: solax-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SOLAX_TOKEN_ID
        sync: false
      - key: SOLAX_WIFI_SN
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///solax_data.db 