services:
  - type: web
    name: solax-dashboard
    env: python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SOLAX_TOKEN_ID
        sync: false
      - key: SOLAX_WIFI_SN
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: solax-db
          property: connectionString

databases:
  - name: solax-db
    databaseName: solax
    user: solax
    plan: free 